name: Deploy To EC2

on:
  push:
    branches:
      - main


jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불어오기
        uses: actions/checkout@v4

      - name: JDK 21버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: application.properties 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES_YML }}" > ./src/main/resources/application.yml


      - name: 테스트 및 빌드하기
        run: |
          chmod 777 ./gradlew
          ./gradlew clean build

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR에 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t tecitlog-server .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag tecitlog-server:latest 654654431456.dkr.ecr.ap-northeast-2.amazonaws.com/tecitlog-server:latest

      - name: ECR에  Docker 이미지 Push
        run: docker push 654654431456.dkr.ecr.ap-northeast-2.amazonaws.com/tecitlog-server:latest

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker stop techitlog-server || true
            docker rm techitlog-server || true
            docker pull ${{ steps.lgoin-ecr-outputs.registry }}/teckitlog-server:latest
            docker run -d --name techitlog-server -p 8080:8080 ${{ steps.lgoin-ecr-outputs.registry }}/teckitlog-server:latest
            
